sudo: required

language: python

python:
  - 3.5
  - 3.6

services:
  - docker

before_install:
  - bash bench_test/before_isntall.sh

# customize test script by enviroment vars.
# env:
#   - REF_RESULT: "テントって飛ぶの？"

script:
  - bash bench_test/script.sh
